# Generated by Django 5.2.15 on 2026-07-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0069_remove_issue_brand_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcd.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcd.publisher'),
        ),
        migrations.AlterField(
            model_name='story',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcd.issue'),
        ),
    ]
