# Generated by Django 5.2.15 on 2026-07-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcd', '0070_alter_issue_series_alter_series_publisher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'get_latest_by': 'id', 'ordering': ['issue_id'], 'permissions': (('can_upload_cover', 'can upload cover'),)},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['series_id', 'sort_code']},
        ),
    ]
